package ch42;
import java.util.Scanner;

//Andrew Erickson December 12 2018

/** This program acts as a test for one's knowledge on capitals of countries across the globe */

public class CountriesCapitalQuiz {
	public static void main(String[] args) {
		Scanner input = new Scanner(System.in);
		
		System.out.println("Your score: " + startTest(input));
	}
	/** This receives a string from the user and when the test is done, it prints the score */
	
	public static int startTest(Scanner input) {
		String[][] capitals = {
			{"United Arab Emirates", "Abu Dhabi"},
				{"Nigeria", "Abuja"},
				{"Ghana", "Accra"},
				{"Pitcairn", "Adamstown"},
				{"Ethiopia", "Addis Ababa"},
				{"Algeria", "Algiers"},
				{"Niue", "Alofi"},
				{"Delaware", "Dover"},
				{"Jordan", "Amman"},
				{"Netherlands", "Amsterdam"},
				{"Andorra", "Andorra la Vella"},
				{"Turkey", "Ankara"},
				{"Madagascar", "Antananarivo"},
				{"Samoa", "Apia"},
				{"Turkmenistan", "Ashgabat"},
				{"Eritrea", "Asmara"},
				{"Kazakhstan", "Astana"},
				{"Paraguay", "Asuncion"},
				{"Greece", "Athens"},
				{"Cook Islands", "Avarua"},
				{"Iraq", "Baghdad"},
				{"Azerbaijan", "Baku"},
				{"Mali", "Bamako"},
				{"Brunei", "Bandar Seri Begawan"},
				{"Thailand", "Bangkok"},
				{"Central African Republic", "Bangui"},
				{"Gambia", "Banjul"},
				{"Saint Kitts and Nevis", "Basseterre"},
				{"China", "Beijing"},
				{"Lebanon", "Beirut"},
				{"Serbia", "Belgrade"},
				{"Belize", "Belmopan"},
				{"Germany", "Berlin"},
				{"Switzerland", "Bern"},
				{"Kyrgyzstan", "Bishkek"},
				{"Guinea-Bissau", "Bissau"},
				{"Colombia", "Bogota"},
				{"Brazil", "Brasillia"},
				{"Slovakia", "Bratislava"},
				{"Republic of the Congo", "Brazzaville"},
				{"Barbados", "Bridgetown"},
				{"Belgium", "Brussels"},
				{"Romania", "Burcharest"},
				{"Hungary", "Budapest"},
				{"Argentina", "Buenos Aires"},
				{"Burundi", "Bujumbura"},
				{"Egypt", "Cairo"},
				{"Australia", "Canberra"},
				{"Venezuela", "Caracas"},
				{"Saint Lucia", "Castries"},
				{"Moldova", "Chisnau"},
				{"Turks and Caicos", "Cockburn Town"},
				{"Guinea", "Conakry"},
				{"Denmark", "Copenhagen"},
				{"Sengal", "Dakar"},
				{"Syria", "Damascus"},
				{"Bangladesh", "Dhaka"},
				{"East Timor", "Dili"},
				{"Djibouti", "Djibouti"},
				{"Tanzania", "Dodoma"},
				{"Qatar", "Doha"},
				{"Ireland", "Dublin"},
				{"Tajikistan", "Dushanbe"},
				{"Sierra Leone", "Freetown"},
				{"Tuvalu", "Funafuti"},
				{"Botswana", "Gabrone"},
				{"Guyana", "Georgetown"},
				{"Gibralter", "Gibralter"},
				{"Guatemala", "Guatemala City"},
				{"Vietnam", "Hanoi"},
				{"Zimbabwe", "Harare"},
				{"Cuba", "Havana"},
				{"Finland", "Helsinki"},
				{"Solomon Islands", "Honiara"},
				{"Pakistan", "Islamabad"},
				{"Indonesia", "Jakarta"},
				{"Isreal/Palestine", "Jerusalem"},
				{"South Sudan", "Juba"},
				{"Afghanistan", "Kabul"},
				{"Uganda", "Kampala"},
				{"Nepal", "Kathmandu"},
				{"Sudan", "Khartoum"},
				{"Ukraine", "Kyiv"},
				{"Rwanda", "Kigali"},
				{"Jamaica", "Kingston"},
				{"St. Vincent", "Kingstown"},
				{"Democratic Rep. of the Congo", "Kinshasa"},
				{"Malaysia", "Kuala Lumpur"},
				{"Kuwait", "Kuwait City"},
				{"Peru", "Lima"},
				{"Portugal", "Libson"},
				{"Slovenia", "Ljubjana"},
				{"Togo", "Lome"},
				{"UK", "London"},
				{"Angola", "Luanda"},
				{"Zambia", "Lusaka"},
				{"Luxembourg", "Luxembourg"},
				{"Spain", "Madrid"},
				{"Equatorial Guinea", "Malabo"},
				{"Maldives", "Male"},
				{"Nicaragua", "Managua"},
				{"Bahrain", "Manama"},
				{"Phillippines", "Manila"},
				{"Mozambique", "Maputo"},
				{"Lesotho", "Maseru"},
				{"Swaziland", "Mbabane"},
				{"Mexico", "Mexico City"},
				{"Belarus", "Minsk"},
				{"Somalia", "Mogadishu"},
				{"Monaco", "Monaco"},
				{"Liberia", "Monrovia"},
				{"Urugauy", "Montevideo"},
				{"Comoros", "Moroni"},
				{"Russia", "Moscow"},
				{"Oman", "Muscat"},
				{"Kenya", "Nairobi"},
				{"Bahamas", "Nassau"},
				{"Myanmar", "Naypyidaw"},
				{"Chad", "N'Djamena"},
				{"India", "New Delhi"},
				{"Palau", "Ngerulmud"},
				{"Niger", "Naimey"},
				{"Cyprus", "Nicosia"},
				{"Mauritania", "Nouakchott"},
				{"Tonga", "Nukuʻalofa"},
				{"Greenland", "Nuuk"},
				{"Norway", "Oslo"},
				{"Canada", "Ottawa"},
				{"Burkina Faso", "Ouagadougou"},
				{"Panama", "Panama City"},
				{"Suriname", "Paramaribo"},
				{"Cambodia", "Phnom Penh"},
				{"Montenegro", "Podgorcia"},
				{"Mauritius", "Port Luis"},
				{"Papua New Guinea", "Port Moresby"},
				{"Vanatu", "Port Vila"},
				{"Haiti", "Port-au-Prince"},
				{"Trinidad and Tobago", "Port of Spain"},
				{"Benin", "Potro-Novo"},
				{"Czech Rep.", "Prague"},
				{"Cape Verde", "Praia"},
				{"South Africa", "Pretoria"},
				{"North Korea", "Pyongyang"},
				{"Ecuador", "Quito"},
				{"Morovvo", "Rabat"},
				{"Iceland", "Reykjavik"},
				{"Latvia", "Riga"},
				{"Saudi Arabia", "Riyadh"},
				{"Italy", "Rome"},
				{"Dominica", "Roseau"},
				{"Costa Rica", "San Jose"},
				{"San Marino", "San Marino"},
				{"El Salvador", "San Salvador"},
				{"Dominican Rep.", "Santo Domingo"},
				{"Sao Tome", "Sao Tome"},
				{"Bosnia and Herz.", "Sarajevo"},
				{"South Korea", "Seoul"},
				{"Singapore", "Singapore"},
				{"Sri Landa", "Colombo"},
				{"Grenada", "St. George"},
				{"Antigua and Barbuda", "St. John's"},
				{"Sweden", "Stockholm"},
				{"Bolivia", "Sucre/La Paz"},
				{"Fiji", "Suva"},
				{"Estonia", "Tallinn"},
				{"Kiribati", "Tarawa"},
				{"Uzbekistan", "Tashkent"},
				{"Georgia", "Tbilisi"},
				{"Honduras", "Tegucigalpa"},
				{"Iran", "Tehran"},
				{"Bhutan", "Thimphu"},
				{"Albania", "Tirana"},
				{"Japan", "Tokyo"},
				{"Tripoli", "Libya"},
				{"Tunisia", "Tunis"},
				{"Mongolia", "Ulaanbaatar"},
				{"Liechtenstein", "Vaduz"},
				{"Malta", "Valletta"},
				{"Anguilla", "The Valley"},
				{"Vatican City", "Vatican City"},
				{"Seychelles", "Victoria"},
				{"Austria", "Vienna"},
				{"Laos", "Vientiane"},
				{"Lithuania", "Vilnius"},
				{"Poland", "Warsaw"},
				{"USA", "Washington D.C."},
				{"New Zealand", "Wellington"},
				{"Namibia", "Windhoek"},
				{"Ivory Coast", "Yamoussoukro"},
				{"Cameroon", "Yaounde"},
				{"Narua", "Yaren"},
				{"Armenia", "Yerevan"},
				{"Croatia", "Zagreb"},

			
		};

		int count = 0;

		for (int i = 0; i < capitals.length; i++) {
			System.out.print("What is the capital of " + capitals[i][0] + "? ");
			if (input.nextLine().toLowerCase().equals(capitals[i][1].toLowerCase())) {
				System.out.println("Your answer is correct");
				count++;
			} else {
				System.out.println("The correct answer should be " + capitals[i][1]);
			}
		}

		return count;
	}
	/** This tests the user's input against the actual correct capital and either increases their score, or prints out what the correct answer was, if wrong */

}